---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
        - name: webserver-simple
          image: ghcr.io/babular05/gitops-cert-level-2-examples:rc2
